variables:
  GRADLE_OPTS: "-Dorg.gradle.parallel=true -Dorg.gradle.configureondemand=true -Dorg.gradle.caching=true"

before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

stages:
- clean
- build
- test
- upload

clean:
  stage: clean
  script: gradle clean -Partifactory_user=$ARTIFACTORY_USER -Partifactory_password=$ARTIFACTORY_PASSWORD -Partifactory_contextUrl=$ARTIFACTORY_CONTEXT_URL -PuseBranch=$CI_COMMIT_REF_NAME
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
    - build
    - .gradle

build:
  stage: build
  script: gradle --build-cache assemble -Partifactory_user=$ARTIFACTORY_USER -Partifactory_password=$ARTIFACTORY_PASSWORD -Partifactory_contextUrl=$ARTIFACTORY_CONTEXT_URL -PuseBranch=$CI_COMMIT_REF_NAME
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
    - build
    - .gradle

test:
  stage: test
  script: gradle check -Partifactory_user=$ARTIFACTORY_USER -Partifactory_password=$ARTIFACTORY_PASSWORD -Partifactory_contextUrl=$ARTIFACTORY_CONTEXT_URL -PuseBranch=$CI_COMMIT_REF_NAME
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
    - build
    - .gradle

upload:
  only:
  - branches
  except:
  - release
  stage: upload
  script: gradle uploadArchives -Partifactory_user=$ARTIFACTORY_USER -Partifactory_password=$ARTIFACTORY_PASSWORD -Partifactory_contextUrl=$ARTIFACTORY_CONTEXT_URL -PuseBranch=$CI_COMMIT_REF_NAME
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
    - build
    - .gradle